name: Ruby GetPWUID Test

on:
  workflow_dispatch:
  push:

jobs:
  ruby-getpwuid-debug:
    name: Build on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          # - arch: ppc64le-selfhosted
          #   runner: ppc64le-rubyid
          - arch: ppc64le
            runner: ubuntu-24.04-ppc64le
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug id info
        run: |
          id
          id -u
          id -g
        working-directory:

      - name: Debug getpwuid()
        run: |
          if [ "$(uname -m)" = "ppc64le" ]; then
            echo "original passwd"
            cat /etc/passwd
            sudo usermod -g "$(id -g)" runner
            id -u 
            id -g
          fi

          
          gcc "${{ github.workspace }}/src/ruby/getpwuid.c" -o get_pw_by_uid
          ./get_pw_by_uid "$(id -u)"

      - name: Check docker
        run: |
          docker info
          
